"""Add technicianTypeId to Technician

Revision ID: 40c9a9e05464
Revises: fe4550e11fbc
Create Date: 2025-10-05 13:39:13.023724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c9a9e05464'
down_revision: Union[str, Sequence[str], None] = 'fe4550e11fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
