"""create technician and technicianType tables

Revision ID: fe4550e11fbc
Revises: 
Create Date: 2025-10-04 15:44:35.189381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fe4550e11fbc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipoTecnico',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('technicianTypeId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('technicianTypeId')
    )
    op.create_index(op.f('ix_tipoTecnico_description'), 'tipoTecnico', ['description'], unique=False)
    op.create_table('technician',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('technicianId', sa.Integer(), nullable=False),
    sa.Column('technicianTypeId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['technicianTypeId'], ['tipoTecnico.technicianTypeId'], ),
    sa.PrimaryKeyConstraint('technicianId')
    )
    op.create_index(op.f('ix_technician_name'), 'technician', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technician_name'), table_name='technician')
    op.drop_table('technician')
    op.drop_index(op.f('ix_tipoTecnico_description'), table_name='tipoTecnico')
    op.drop_table('tipoTecnico')
    # ### end Alembic commands ###
